name: funkmeup
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_blue: ^0.7.3
  flame: ^0.29.4
  esense_flutter: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - assets/images/slidefront.png
    - assets/images/slideleft.png
    - assets/images/slideright.png
    - assets/images/spin.png
    - assets/images/start.png
    - assets/images/quit.png
    - assets/images/title.png
    - assets/audio/september.mp3
    - assets/audio/intro.mp3
    - assets/audio/play.mp3


  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.ttf
